// <auto-generated />
using System;
using EasyJamDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyJamDAL.Migrations
{
    [DbContext(typeof(EasyJamContext))]
    [Migration("20230826090250_JamDB")]
    partial class JamDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyJamDAL.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EncodedPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb1cf296-3bb7-4d3a-b885-0ac8fd45c7a1"),
                            Email = "Test@test.com",
                            EncodedPassword = new byte[] { 146, 25, 219, 89, 59, 125, 56, 49, 142, 175, 121, 167, 254, 85, 140, 36, 4, 90, 13, 50, 155, 108, 200, 182, 93, 34, 227, 155, 85, 4, 131, 16, 215, 145, 130, 94, 142, 11, 188, 248, 154, 19, 134, 31, 173, 243, 103, 100, 228, 78, 209, 217, 169, 117, 119, 254, 105, 15, 35, 34, 143, 190, 223, 52 },
                            FirstName = "Rocco",
                            LastName = "Pasanisi",
                            Salt = new Guid("6f2b1ff4-6df0-4bd7-bbea-ac9536f1eb41")
                        });
                });

            modelBuilder.Entity("EasyJamDAL.Entities.JamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jams");
                });

            modelBuilder.Entity("EasyJamDAL.Entities.Musicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instrument1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musiciens");
                });
#pragma warning restore 612, 618
        }
    }
}
