// <auto-generated />
using System;
using EasyJamDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyJamDAL.Migrations
{
    [DbContext(typeof(EasyJamContext))]
    [Migration("20231218140234_sessionTimeAdded")]
    partial class sessionTimeAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyJamDAL.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EncodedPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8eb81c2b-8f96-4cc9-9006-1bcdaa41e30c"),
                            Email = "Test@test.com",
                            EncodedPassword = new byte[] { 123, 71, 48, 54, 97, 188, 196, 149, 134, 119, 127, 149, 19, 190, 58, 76, 46, 85, 116, 86, 207, 194, 83, 223, 28, 70, 89, 77, 182, 48, 5, 161, 162, 42, 30, 177, 187, 100, 18, 62, 190, 65, 98, 193, 184, 131, 208, 18, 61, 246, 166, 180, 78, 248, 254, 128, 161, 18, 196, 88, 64, 95, 238, 183 },
                            FirstName = "Rocco",
                            LastName = "Pasanisi",
                            Salt = new Guid("fdb83384-5396-4591-8878-3039edb58f62")
                        });
                });

            modelBuilder.Entity("EasyJamDAL.Entities.JamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRandom")
                        .HasColumnType("bit");

                    b.Property<string>("Keys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jams");
                });

            modelBuilder.Entity("EasyJamDAL.Entities.Musicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instrument1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musiciens");
                });
#pragma warning restore 612, 618
        }
    }
}
