// <auto-generated />
using System;
using EasyJamDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyJamDAL.Migrations
{
    [DbContext(typeof(EasyJamContext))]
    [Migration("20231212092231_boolForRandom")]
    partial class boolForRandom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyJamDAL.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EncodedPassword")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd6ec335-8ee4-4b42-a2ba-29d66c185810"),
                            Email = "Test@test.com",
                            EncodedPassword = new byte[] { 26, 131, 106, 178, 63, 207, 244, 104, 132, 244, 56, 251, 81, 115, 20, 5, 191, 52, 216, 79, 255, 237, 171, 51, 46, 56, 173, 255, 119, 183, 158, 202, 21, 216, 44, 232, 55, 19, 64, 9, 66, 69, 188, 224, 143, 229, 208, 44, 200, 215, 194, 154, 116, 32, 35, 25, 52, 42, 115, 51, 159, 106, 103, 49 },
                            FirstName = "Rocco",
                            LastName = "Pasanisi",
                            Salt = new Guid("d23e5346-8f7c-4f2c-8265-d3f0092af0a4")
                        });
                });

            modelBuilder.Entity("EasyJamDAL.Entities.JamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtr2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRandom")
                        .HasColumnType("bit");

                    b.Property<string>("Keys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mic2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jams");
                });

            modelBuilder.Entity("EasyJamDAL.Entities.Musicien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instrument1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musiciens");
                });
#pragma warning restore 612, 618
        }
    }
}
